In [1]:
import requests
import datetime
import time
import os, sys
import pandas as pd
sys.path.append(os.path.join(os.path.dirname(os.getcwd()), "."))
from config.filters import SPESE, INCOME, RIMBORSI, INVESTIMENTI, BUONI_PASTO
from dotenv import load_dotenv
load_dotenv()
WALLET_API_TOKEN = os.getenv("WALLET_API_TOKEN")

In [2]:
def call_wallet_api(endpoint: str, args: dict = None, base_url = "https://rest.budgetbakers.com/wallet"):
    headers = {"Authorization": f"Bearer {WALLET_API_TOKEN}"}
    request_url = f"{base_url}/{endpoint}"
    # send the request with a payload of params
    response = requests.get(request_url, headers=headers, params=args)
    if response.status_code == 200:
        return response.json()
    else:
        raise Exception(f"API call failed with status code {response.status_code}: {response.text}")

In [3]:
# /accounts defaults to a page size of 10 -> paginate or accounts get silently dropped
accounts = {}
i = 0
while True:
    page = call_wallet_api("v1/api/accounts", args={"limit": 100, "offset": i * 100})["accounts"]
    if not page:
        break
    for account in page:
        accounts[account["name"]] = account["id"]
    i += 1

In [4]:
accounts

{'Banco BPM': '67ea39ef-ac84-48ac-9c48-ff8f9049a1c1',
 'Buoni pasto': '2b044f45-7a57-4095-bbad-9cd2f49a7fa0',
 'Cash': '7296cfee-ff1a-497f-8382-fcc7a265e23a',
 'Fineco': '355bbb52-ecb7-4717-b170-9eeb2cd0b063',
 'Intesa San Paolo': '3b544b6c-9653-4968-ac71-daa82252b738',
 'PayPal': '8cd5ee39-e099-47e7-90e1-03585a866e7b',
 'Prepaid XME plus': '1a5c2400-70b0-421f-8bc4-39f95bf879f1',
 'Revolut': '8ff2d76e-f475-4af6-b265-f677b2c1996a',
 'Satispay': 'cf067959-f56a-4cb0-bd6d-ace82640d3b4',
 'Scalable Capital': '6e418d8c-ab2b-4977-abc1-f1ce7a864506',
 'Trade Republic': '24df231a-1cc3-4bcb-8528-242c4889bc1c'}

In [15]:
first_day_of_this_month = datetime.date.today().replace(day=1)
first_day_of_last_month = (first_day_of_this_month - datetime.timedelta(days=1)).replace(day=1).isoformat()
last_date_of_last_month = (first_day_of_this_month - datetime.timedelta(days=1)).isoformat()
# first_day_of_last_month = (datetime.date.today() - datetime.timedelta(days=1)).isoformat()
# last_date_of_last_month = (datetime.date.today()).isoformat()
# first_day_of_last_month = "2020-01-01"
# last_date_of_last_month = "2026-06-19"
print(f"Fetching records from {first_day_of_last_month} to {last_date_of_last_month}")

records_df = pd.DataFrame()

i = 0

for account_name, account_id in accounts.items():
    while True:    
        n_records_retrieved = i * 200

        args = {
                "accountId": account_id,
                "recordDate": [f"gte.{first_day_of_last_month}", f"lte.{last_date_of_last_month}"],
                "limit": 200,
                "offset": n_records_retrieved
            }
        time.sleep(1)
        print(f"Fetching records for account {account_name} with offset {n_records_retrieved}")
        records = call_wallet_api("v1/api/records", args=args)

        if len(records['records']) > 0:
            account_records = records['records']
            for record in account_records:
                cat_id = record['category']['id']
                cat_name = record['category']['name']
                date = record['recordDate']
                amount = record['amount']["value"]
                label_ids = [label['id'] for label in record.get('labels', [])]
                label_names = [label['name'] for label in record.get('labels', [])]

                new_row = {
                    "account": account_name,
                    "amount": amount,
                    "date": date,
                    "category_id": cat_id,
                    "category_name": cat_name,
                    "label_ids": label_ids,
                    "label_names": label_names
                }
                records_df = pd.concat([records_df, pd.DataFrame([new_row])], ignore_index=True)
                
            i += 1
        else:
            i = 0
            break

Fetching records from 2026-05-01 to 2026-05-31
Fetching records for account Banco BPM with offset 0
Fetching records for account Banco BPM with offset 200
Fetching records for account Buoni pasto with offset 0
Fetching records for account Buoni pasto with offset 200
Fetching records for account Cash with offset 0
Fetching records for account Cash with offset 200
Fetching records for account Fineco with offset 0
Fetching records for account Intesa San Paolo with offset 0
Fetching records for account Intesa San Paolo with offset 200
Fetching records for account PayPal with offset 0
Fetching records for account PayPal with offset 200
Fetching records for account Prepaid XME plus with offset 0
Fetching records for account Revolut with offset 0
Fetching records for account Revolut with offset 200
Fetching records for account Satispay with offset 0
Fetching records for account Scalable Capital with offset 0
Fetching records for account Trade Republic with offset 0
Fetching records for account Trade Republic with offset 200

In [16]:
records_df.sort_values(by='date', ascending=False)

,account,amount,date,category_id,category_name,label_ids,label_names
52,Trade Republic,-6.80,2026-05-31T20:10:19.985Z,5c5c03e8-000a-8000-8000-000000000000,Groceries,[],[]
12,Cash,-8.00,2026-05-31T16:26:39.691Z,5c5c2af9-006e-8000-8000-000000000000,Smarrimento,[],[]
53,Trade Republic,-6.00,2026-05-30T23:27:49.798Z,5c5c03ea-000a-8000-8000-000000000000,Bar cafe,[],[]
54,Trade Republic,-7.00,2026-05-30T23:27:49.798Z,5c5c03ea-000a-8000-8000-000000000000,Bar cafe,[],[]
55,Trade Republic,-14.64,2026-05-30T13:56:13.784Z,5c5c03e8-000a-8000-8000-000000000000,Groceries,[],[]
...,...,...,...,...,...,...,...
132,Trade Republic,-11.93,2026-05-01T16:48:19.894Z,5c5c1b5b-0046-8000-8000-000000000000,"Software, apps, games",[9344968d-88e1-4951-9c87-909a16ee4a42],[Loomy]
51,Revolut,10.00,2026-05-01T14:17:35.456Z,5c5c4e21-00c8-8000-8000-000000000000,Transfer,[],[]
133,Trade Republic,-10.00,2026-05-01T14:17:35.456Z,5c5c4e21-00c8-8000-8000-000000000000,Transfer,[],[]
134,Trade Republic,-105.35,2026-05-01T12:37:04.092Z,5c5c177d-003c-8000-8000-000000000000,Life & Entertainment,[],[]
135,Trade Republic,3.09,2026-05-01T08:32:59.827Z,7af26741-a212-47da-a50c-baeb717e9db4,Interessi,[],[]

In [17]:
records_df.shape

(136, 7)

In [18]:
spese_df = records_df[records_df['category_id'].isin(SPESE['categories'].keys()) &
           (records_df['amount'] < 0)]
spese_amount = round(spese_df.amount.sum(), 2)

In [19]:
spese_df.sort_values(by='date', ascending=False).head(3)

,account,amount,date,category_id,category_name,label_ids,label_names
52,Trade Republic,-6.8,2026-05-31T20:10:19.985Z,5c5c03e8-000a-8000-8000-000000000000,Groceries,[],[]
12,Cash,-8.0,2026-05-31T16:26:39.691Z,5c5c2af9-006e-8000-8000-000000000000,Smarrimento,[],[]
53,Trade Republic,-6.0,2026-05-30T23:27:49.798Z,5c5c03ea-000a-8000-8000-000000000000,Bar cafe,[],[]

In [20]:
income_df = records_df[records_df['category_id'].isin(INCOME['categories'].keys()) &
           (records_df['amount'] > 0)]
income_amount = round(income_df.amount.sum(), 2)

In [21]:
rimborsi_df = records_df[records_df['category_id'].isin(RIMBORSI['categories'].keys()) &
           (records_df['amount'] > 0)]
rimborsi_amount = round(rimborsi_df.amount.sum(), 2)

In [22]:
investimenti_df = records_df[records_df['category_id'].isin(INVESTIMENTI['categories'].keys()) &
           (records_df['amount'] > 0)]
investimenti_amount = round(investimenti_df.amount.sum(), 2)

In [23]:
buoni_pasto_df = records_df[records_df['category_id'].isin(BUONI_PASTO['categories'].keys()) &
           (records_df['amount'] > 0)]
buoni_pasto_amount = round(buoni_pasto_df.amount.sum(), 2)

In [24]:
svincolati = round(income_amount + rimborsi_amount + spese_amount, 2)
print(f"Spese: {spese_amount}€")
print(f"Income: {income_amount}€")
print(f"Rimborsi: {rimborsi_amount}€")
print("\n")
print(f"Buoni pasto: {buoni_pasto_amount}€")
print(f"Svincolati: {svincolati}€")
print(f"Investimenti: {investimenti_amount}€")

Spese: -2481.48€
Income: 2466.41€
Rimborsi: 249.4€


Buoni pasto: 31.0€
Svincolati: 234.33€
Investimenti: 500.29€

Categories non mappate

In [15]:
records_df[records_df['category_id'].isin([
    'ea566b98-446f-40eb-8071-f5289acf6716',
    #  'dcd71755-22e5-4f87-baa7-b07ad5cbbcb8',
     'd259f3dc-0630-4845-ad3b-af4facc22e0d',
     'a6daf078-746f-4de8-8d53-ddeab5abfe83',
    #  '0285055c-755c-4008-a5ef-84a8f2e77f0b',
    #  '68b6ced6-1c86-4534-8c88-704e0de6519e', # Tempo libero
     'dcd71755-22e5-4f87-baa7-b07ad5cbbcb8'
     ]
                                          )].sort_values('date')

Empty DataFrame
Columns: [account, amount, date, category_id, category_name, label_ids, label_names]
Index: []

### Categories

In [38]:
records_categories = records_df['category_id'].unique()

In [51]:
# select the ids of records_categories that are not present in categoreis['id']
cats_not_in_api = pd.Series(records_categories).isin(categories_df['id'])
missing_categories = records_categories[~cats_not_in_api]

In [52]:
missing_categories

<StringArray>
[]
Length: 0, dtype: str

In [43]:
categories = call_wallet_api("v1/api/categories")

In [44]:
categories

{'categories': [{'id': '5c5c1f44-0050-8000-8000-000000000000',
   'name': 'Advisory',
   'group': {'id': 'financial_expenses', 'name': 'Financial expenses'},
   'systemId': 'financial_expenses__advisory',
   'color': '#00BFA5',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2026-06-18T22:14:57.253Z'},
  {'id': '5c5c1f45-0050-8000-8000-000000000000',
   'name': 'Commissioni',
   'group': {'id': 'financial_expenses', 'name': 'Financial expenses'},
   'systemId': 'financial_expenses__charges_fees',
   'color': '#00BFA5',
   'cardinality': 'must',
   'customCategory': False,
   'customName': True,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2021-10-02T08:35:12.077Z'},
  {'id': '5c5c1f48-0050-8000-8000-000000000000',
   'name': 'Financial expenses',
   'group': {'id': 'financial_expenses', 'name': 'Financial expenses'},
   'systemId': 'financial_expenses__general',
   'color': '#00BFA5',
   'cardinality': 'must',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-22T12:01:48.360Z'},
  {'id': '5c5c1f43-0050-8000-8000-000000000000',
   'name': 'Fines',
   'group': {'id': 'financial_expenses', 'name': 'Financial expenses'},
   'systemId': 'financial_expenses__fines',
   'color': '#00BFA5',
   'cardinality': 'must',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2021-02-24T09:44:11.024Z'},
  {'id': '5c5c1f41-0050-8000-8000-000000000000',
   'name': 'Insurances',
   'group': {'id': 'financial_expenses', 'name': 'Financial expenses'},
   'systemId': 'financial_expenses__insurances',
   'color': '#00BFA5',
   'cardinality': 'need',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2026-06-18T22:14:57.253Z'},
  {'id': '5c5c1f42-0050-8000-8000-000000000000',
   'name': 'Loan, interests',
   'group': {'id': 'financial_expenses', 'name': 'Financial expenses'},
   'systemId': 'financial_expenses__loan_interests',
   'color': '#00BFA5',
   'cardinality': 'must',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-23T14:10:42.242Z'},
  {'id': '5c5c1f47-0050-8000-8000-000000000000',
   'name': 'Refund',
   'group': {'id': 'financial_expenses', 'name': 'Financial expenses'},
   'systemId': 'financial_expenses__aliments',
   'color': '#00BFA5',
   'cardinality': 'must',
   'customCategory': False,
   'customName': True,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-06-14T12:55:53.119Z'},
  {'id': '5c5c232b-005a-8000-8000-000000000000',
   'name': 'Savings',
   'group': {'id': 'investments', 'name': 'Financial expenses'},
   'systemId': 'investments__savings',
   'color': '#FF4081',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-22T12:02:06.035Z'},
  {'id': '5c5c1f40-0050-8000-8000-000000000000',
   'name': 'Taxes',
   'group': {'id': 'financial_expenses', 'name': 'Financial expenses'},
   'systemId': 'financial_expenses__taxes',
   'color': '#00BFA5',
   'cardinality': 'must',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2021-04-26T16:31:23.685Z'},
  {'id': '5c5c03ea-000a-8000-8000-000000000000',
   'name': 'Bar cafe',
   'group': {'id': 'food_and_drinks', 'name': 'Food & Drinks'},
   'systemId': 'food_and_drinks__bar_cafe',
   'color': '#FF3D00',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-01-04T13:01:30.620Z'},
  {'id': '5c5c03eb-000a-8000-8000-000000000000',
   'name': 'Food & Drinks',
   'group': {'id': 'food_and_drinks', 'name': 'Food & Drinks'},
   'systemId': 'food_and_drinks__general',
   'color': '#FF3D00',
   'cardinality': 'need',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-02-15T09:21:50.691Z'},
  {'id': '5c5c03e8-000a-8000-8000-000000000000',
   'name': 'Groceries',
   'group': {'id': 'food_and_drinks', 'name': 'Food & Drinks'},
   'systemId': 'food_and_drinks__groceries',
   'color': '#FF3D00',
   'cardinality': 'need',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-23T14:14:48.703Z'},
  {'id': '5c5c03e9-000a-8000-8000-000000000000',
   'name': 'Restaurants & fast food',
   'group': {'id': 'food_and_drinks', 'name': 'Food & Drinks'},
   'systemId': 'food_and_drinks__restaurants_fast_food',
   'color': '#FF3D00',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-01-19T03:05:55.906Z'},
  {'id': '5c5c0bba-001e-8000-8000-000000000000',
   'name': 'Energy & utilities',
   'group': {'id': 'housing', 'name': 'Housing'},
   'systemId': 'housing__energy_utilities',
   'color': '#FFA726',
   'cardinality': 'must',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-23T14:14:48.715Z'},
  {'id': '5c5c0bbd-001e-8000-8000-000000000000',
   'name': 'Housing',
   'group': {'id': 'housing', 'name': 'Housing'},
   'systemId': 'housing__general',
   'color': '#FFA726',
   'cardinality': 'must',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-23T13:57:26.421Z'},
  {'id': '5c5c0bc2-001e-8000-8000-000000000000',
   'name': 'Insurance (Housing)',
   'group': {'id': 'housing', 'name': 'Housing'},
   'systemId': 'housing__insurance',
   'color': '#FFA726',
   'cardinality': 'need',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-20T19:33:30.872Z'},
  {'id': '5c5c0bbc-001e-8000-8000-000000000000',
   'name': 'Maintenance & repairs',
   'group': {'id': 'housing', 'name': 'Housing'},
   'systemId': 'housing__maintenance_repairs',
   'color': '#FFA726',
   'cardinality': 'need',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-20T20:20:23.529Z'},
  {'id': '5c5c0bb8-001e-8000-8000-000000000000',
   'name': 'Rent',
   'group': {'id': 'housing', 'name': 'Housing'},
   'systemId': 'housing__rent',
   'color': '#FFA726',
   'cardinality': 'must',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2022-08-11T15:27:17.433Z'},
  {'id': '5c5c0bb9-001e-8000-8000-000000000000',
   'name': 'Rete telefonica fissa',
   'group': {'id': 'housing', 'name': 'Housing'},
   'systemId': 'housing__mortgage',
   'color': '#FFA000',
   'cardinality': 'must',
   'customCategory': False,
   'customName': True,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-12-01T11:59:25.482Z'},
  {'id': '5c5c0bbb-001e-8000-8000-000000000000',
   'name': 'Services',
   'group': {'id': 'housing', 'name': 'Housing'},
   'systemId': 'housing__services',
   'color': '#FFA726',
   'cardinality': 'must',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-09-27T15:10:02.939Z'},
  {'id': '5c5c2719-0064-8000-8000-000000000000',
   'name': 'Bonus',
   'group': {'id': 'income', 'name': 'Income'},
   'systemId': 'income__aliments',
   'color': '#FFB300',
   'cardinality': 'want',
   'customCategory': False,
   'customName': True,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-23T13:57:55.157Z'},
  {'id': '5c5c271a-0064-8000-8000-000000000000',
   'name': 'Gifts',
   'group': {'id': 'income', 'name': 'Income'},
   'systemId': 'income__gifts',
   'color': '#FBC02D',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-01-02T10:49:10.152Z'},
  {'id': '5c5c271b-0064-8000-8000-000000000000',
   'name': 'Income',
   'group': {'id': 'income', 'name': 'Income'},
   'systemId': 'income__general',
   'color': '#FBC02D',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-22T16:20:05.314Z'},
  {'id': '5c5c2711-0064-8000-8000-000000000000',
   'name': 'Interest, dividends',
   'group': {'id': 'income', 'name': 'Income'},
   'systemId': 'income__interest_dividends',
   'color': '#FFCD01',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2026-06-18T22:14:57.433Z'},
  {'id': '5c5c2715-0064-8000-8000-000000000000',
   'name': 'Lending, renting',
   'group': {'id': 'income', 'name': 'Income'},
   'systemId': 'income__lending_renting',
   'color': '#FBC02D',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-22T20:26:46.127Z'},
  {'id': '5c5c2717-0064-8000-8000-000000000000',
   'name': 'Lottery, gambling (Income)',
   'group': {'id': 'income', 'name': 'Income'},
   'systemId': 'income__lottery_gambling',
   'color': '#FBC02D',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-22T11:49:25.759Z'},
  {'id': '5c5c2716-0064-8000-8000-000000000000',
   'name': 'Paghetta',
   'group': {'id': 'income', 'name': 'Income'},
   'systemId': 'income__checks_coupons',
   'color': '#FFB300',
   'cardinality': 'want',
   'customCategory': False,
   'customName': True,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-12-22T14:38:47.028Z'},
  {'id': '5c5c2718-0064-8000-8000-000000000000',
   'name': 'Rimborsi',
   'group': {'id': 'income', 'name': 'Income'},
   'systemId': 'income__refunds',
   'color': '#FBC02D',
   'cardinality': 'want',
   'customCategory': False,
   'customName': True,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-23T13:55:36.971Z'},
  {'id': '5c5c2714-0064-8000-8000-000000000000',
   'name': 'Rimborsi calcio',
   'group': {'id': 'income', 'name': 'Income'},
   'systemId': 'income__dues_grants',
   'color': '#FBC02D',
   'cardinality': 'want',
   'customCategory': False,
   'customName': True,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2021-10-29T18:12:37.814Z'},
  {'id': '5c5c2713-0064-8000-8000-000000000000',
   'name': 'Ripetizioni',
   'group': {'id': 'income', 'name': 'Income'},
   'systemId': 'income__rental_income',
   'color': '#FBC02D',
   'cardinality': 'want',
   'customCategory': False,
   'customName': True,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2022-03-22T16:57:43.133Z'},
  {'id': '5c5c2712-0064-8000-8000-000000000000',
   'name': 'Sale',
   'group': {'id': 'income', 'name': 'Income'},
   'systemId': 'income__sale',
   'color': '#FBC02D',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-01-25T22:19:01.013Z'},
  {'id': '5c5c2710-0064-8000-8000-000000000000',
   'name': 'Wage, invoices',
   'group': {'id': 'income', 'name': 'Income'},
   'systemId': 'income__wage_invoices',
   'color': '#FFB300',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-23T13:58:11.897Z'},
  {'id': 'a5cdc9ef-d31f-4c16-8840-421165b76037',
   'name': 'Buoni pasto',
   'group': {'id': 'income', 'name': 'Income'},
   'color': '#FBC02D',
   'cardinality': 'want',
   'customCategory': True,
   'customName': False,
   'archived': False,
   'enabled': True,
   'parentId': '5c5c2719-0064-8000-8000-000000000000',
   'createdAt': '2024-02-07T18:35:20.340Z',
   'updatedAt': '2024-02-07T18:35:20.340Z'},
  {'id': '892593d3-451c-45e5-8518-9c233abd38db',
   'name': 'Premi',
   'group': {'id': 'income', 'name': 'Income'},
   'color': '#FBC02D',
   'cardinality': 'want',
   'customCategory': True,
   'customName': False,
   'archived': False,
   'enabled': True,
   'parentId': '5c5c2719-0064-8000-8000-000000000000',
   'createdAt': '2023-12-04T14:55:00.291Z',
   'updatedAt': '2023-12-04T14:55:00.291Z'},
  {'id': '5c5c232a-005a-8000-8000-000000000000',
   'name': 'Fin. investments',
   'group': {'id': 'investments', 'name': 'Investments'},
   'systemId': 'investments__fin_investments',
   'color': '#FF4081',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-11-14T10:23:28.061Z'},
  {'id': '5c5c232c-005a-8000-8000-000000000000',
   'name': 'Interests and Dividends',
   'group': {'id': 'investments', 'name': 'Investments'},
   'systemId': 'investments__collections',
   'color': '#EC407A',
   'cardinality': 'none',
   'customCategory': False,
   'customName': True,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2024-10-01T07:04:18.871Z'},
  {'id': '5c5c232d-005a-8000-8000-000000000000',
   'name': 'Investments',
   'group': {'id': 'investments', 'name': 'Investments'},
   'systemId': 'investments__general',
   'color': '#FF4081',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-06-14T12:57:04.187Z'},
  {'id': '5c5c2328-005a-8000-8000-000000000000',
   'name': 'Realty',
   'group': {'id': 'investments', 'name': 'Investments'},
   'systemId': 'investments__realty',
   'color': '#FF4081',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2022-08-13T10:11:06.949Z'},
  {'id': '5c5c2329-005a-8000-8000-000000000000',
   'name': 'Vehicles, chattels',
   'group': {'id': 'investments', 'name': 'Investments'},
   'systemId': 'investments__vehicles_chattels',
   'color': '#FF4081',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2026-06-18T22:14:57.253Z'},
  {'id': 'a04096d4-7436-47dd-b6a0-5f545e7eff20',
   'name': 'Dividends',
   'group': {'id': 'investments', 'name': 'Investments'},
   'color': '#FF4081',
   'cardinality': 'want',
   'customCategory': True,
   'customName': False,
   'archived': False,
   'enabled': True,
   'parentId': '5c5c232c-005a-8000-8000-000000000000',
   'createdAt': '2024-10-01T07:03:09.390Z',
   'updatedAt': '2024-10-01T07:03:09.390Z'},
  {'id': '7af26741-a212-47da-a50c-baeb717e9db4',
   'name': 'Interessi',
   'group': {'id': 'investments', 'name': 'Investments'},
   'color': '#FF4081',
   'cardinality': 'want',
   'customCategory': True,
   'customName': False,
   'archived': False,
   'enabled': True,
   'parentId': '5c5c232c-005a-8000-8000-000000000000',
   'createdAt': '2024-10-01T07:02:39.953Z',
   'updatedAt': '2024-10-01T07:02:39.953Z'},
  {'id': '5c5c1772-003c-8000-8000-000000000000',
   'name': 'Active sport, fitness',
   'group': {'id': 'life_entertainment', 'name': 'Life & Entertainment'},
   'systemId': 'life_entertainment__active_sport_fitness',
   'color': '#64DD17',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-23T14:14:48.736Z'},
  {'id': '5c5c177b-003c-8000-8000-000000000000',
   'name': 'Alcohol, tobacco',
   'group': {'id': 'life_entertainment', 'name': 'Life & Entertainment'},
   'systemId': 'life_entertainment__alcohol_tobacco',
   'color': '#64DD17',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-08-09T17:48:59.251Z'},
  {'id': '5c5c1777-003c-8000-8000-000000000000',
   'name': 'Books, audio, subscription',
   'group': {'id': 'life_entertainment', 'name': 'Life & Entertainment'},
   'systemId': 'life_entertainment__books_audio_subscription',
   'color': '#64DD17',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-06-09T15:40:41.860Z'},
  {'id': '5c5c177a-003c-8000-8000-000000000000',
   'name': 'Charity, gifts',
   'group': {'id': 'life_entertainment', 'name': 'Life & Entertainment'},
   'systemId': 'life_entertainment__charity_gifts',
   'color': '#64DD17',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-03-06T15:42:34.701Z'},
  {'id': '5c5c1773-003c-8000-8000-000000000000',
   'name': 'Culture, sport events',
   'group': {'id': 'life_entertainment', 'name': 'Life & Entertainment'},
   'systemId': 'life_entertainment__culture_sport_events',
   'color': '#64DD17',
   'cardinality': 'want',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-08-08T16:26:50.175Z'},
  {'id': '5c5c1776-003c-8000-8000-000000000000',
   'name': 'Education & development',
   'group': {'id': 'life_entertainment', 'name': 'Life & Entertainment'},
   'systemId': 'life_entertainment__education_development',
   'color': '#64DD17',
   'cardinality': 'need',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2020-01-07T10:49:24.178Z'},
  {'id': '5c5c1770-003c-8000-8000-000000000000',
   'name': 'Health care & doctor',
   'group': {'id': 'life_entertainment', 'name': 'Life & Entertainment'},
   'systemId': 'life_entertainment__health_care_doctor',
   'color': '#64DD17',
   'cardinality': 'need',
   'customCategory': False,
   'customName': False,
   'archived': False,
   'enabled': True,
   'createdAt': '2026-06-18T22:14:57.253Z',
   'updatedAt': '2019-12-23T14:07:23.398Z'},
  {'id': '5c5c1775-003c-8000-8000-000000000000',
   'name': 'Hobbies',
   'group': {'id': 'life_entertainment', 'name': 'Life & Entertainment'},

In [45]:
categories_df = pd.DataFrame()

i = 0
while True:
    n_cat_retrieved = i * 100
    args = {
        "limit": 100,
        "offset": n_cat_retrieved
    }
    cat_page = call_wallet_api("v1/api/categories", args=args)
    
    if not cat_page['categories']:  # Stop when no more items are returned
        break
    
    for cat in cat_page['categories']:
        id = cat['id']
        name = cat['name']
        categories_df = pd.concat([categories_df, pd.DataFrame([{"id": id, "name": name}])], ignore_index=True)
    
    i += 1

In [46]:
categories_df

                                      id                 name
0   5c5c1f44-0050-8000-8000-000000000000             Advisory
1   5c5c1f45-0050-8000-8000-000000000000          Commissioni
2   5c5c1f48-0050-8000-8000-000000000000   Financial expenses
3   5c5c1f43-0050-8000-8000-000000000000                Fines
4   5c5c1f41-0050-8000-8000-000000000000           Insurances
..                                   ...                  ...
89  5c5c1389-0032-8000-8000-000000000000              Parking
90  5c5c1f46-0032-8000-8000-000000000000             Pedaggio
91  5c5c138b-0032-8000-8000-000000000000              Rentals
92  5c5c138c-0032-8000-8000-000000000000              Vehicle
93  5c5c138a-0032-8000-8000-000000000000  Vehicle maintenance

[94 rows x 2 columns]

In [21]:
for i, row in categories_df.iterrows():
    print(row['name'], row['id'])

Advisory 5c5c1f44-0050-8000-8000-000000000000
Commissioni 5c5c1f45-0050-8000-8000-000000000000
Financial expenses 5c5c1f48-0050-8000-8000-000000000000
Fines 5c5c1f43-0050-8000-8000-000000000000
Insurances 5c5c1f41-0050-8000-8000-000000000000
Loan, interests 5c5c1f42-0050-8000-8000-000000000000
Refund 5c5c1f47-0050-8000-8000-000000000000
Savings 5c5c232b-005a-8000-8000-000000000000
Taxes 5c5c1f40-0050-8000-8000-000000000000
Bar cafe 5c5c03ea-000a-8000-8000-000000000000
Food & Drinks 5c5c03eb-000a-8000-8000-000000000000
Groceries 5c5c03e8-000a-8000-8000-000000000000
Restaurants & fast food 5c5c03e9-000a-8000-8000-000000000000
Energy & utilities 5c5c0bba-001e-8000-8000-000000000000
Housing 5c5c0bbd-001e-8000-8000-000000000000
Insurance (Housing) 5c5c0bc2-001e-8000-8000-000000000000
Maintenance & repairs 5c5c0bbc-001e-8000-8000-000000000000
Rent 5c5c0bb8-001e-8000-8000-000000000000
Rete telefonica fissa 5c5c0bb9-001e-8000-8000-000000000000
Services 5c5c0bbb-001e-8000-8000-000000000000
Bonus 5c5c2719-0064-8000-8000-000000000000
Gifts 5c5c271a-0064-8000-8000-000000000000
Income 5c5c271b-0064-8000-8000-000000000000
Interest, dividends 5c5c2711-0064-8000-8000-000000000000
Lending, renting 5c5c2715-0064-8000-8000-000000000000
Lottery, gambling (Income) 5c5c2717-0064-8000-8000-000000000000
Paghetta 5c5c2716-0064-8000-8000-000000000000
Rimborsi 5c5c2718-0064-8000-8000-000000000000
Rimborsi calcio 5c5c2714-0064-8000-8000-000000000000
Ripetizioni 5c5c2713-0064-8000-8000-000000000000
Sale 5c5c2712-0064-8000-8000-000000000000
Wage, invoices 5c5c2710-0064-8000-8000-000000000000
Buoni pasto a5cdc9ef-d31f-4c16-8840-421165b76037
Premi 892593d3-451c-45e5-8518-9c233abd38db
Fin. investments 5c5c232a-005a-8000-8000-000000000000
Interests and Dividends 5c5c232c-005a-8000-8000-000000000000
Investments 5c5c232d-005a-8000-8000-000000000000
Realty 5c5c2328-005a-8000-8000-000000000000
Vehicles, chattels 5c5c2329-005a-8000-8000-000000000000
Dividends a04096d4-7436-47dd-b6a0-5f545e7eff20
Interessi 7af26741-a212-47da-a50c-baeb717e9db4
Active sport, fitness 5c5c1772-003c-8000-8000-000000000000
Alcohol, tobacco 5c5c177b-003c-8000-8000-000000000000
Books, audio, subscription 5c5c1777-003c-8000-8000-000000000000
Charity, gifts 5c5c177a-003c-8000-8000-000000000000
Culture, sport events 5c5c1773-003c-8000-8000-000000000000
Education & development 5c5c1776-003c-8000-8000-000000000000
Health care & doctor 5c5c1770-003c-8000-8000-000000000000
Hobbies 5c5c1775-003c-8000-8000-000000000000
Holidays, trips, hotels 5c5c1779-003c-8000-8000-000000000000
Life & Entertainment 5c5c177d-003c-8000-8000-000000000000
Life events 5c5c1774-003c-8000-8000-000000000000
Lottery, gambling (Life & Entertainment) 5c5c177c-003c-8000-8000-000000000000
Tv, streaming 5c5c1778-003c-8000-8000-000000000000
Wellness & beauty 5c5c1771-003c-8000-8000-000000000000
Others 5c5c2af8-006e-8000-8000-000000000000
Smarrimento 5c5c2af9-006e-8000-8000-000000000000
Leti da3fcf77-52a4-41ca-bba3-bd06493ba159
Internet 5c5c1b5a-0046-8000-8000-000000000000
PC, Communication 5c5c1b5d-0046-8000-8000-000000000000
Phone, cell phones 5c5c1b59-0046-8000-8000-000000000000
Postal services 5c5c1b5c-0046-8000-8000-000000000000
Software, apps, games 5c5c1b5b-0046-8000-8000-000000000000
Clothes & shoes 5c5c07d0-0014-8000-8000-000000000000
Department Stores 5c5c07dc-0014-8000-8000-000000000000
Drugstore 5c5c07db-0014-8000-8000-000000000000
Electronics & accessories 5c5c07d6-0014-8000-8000-000000000000
Free time 5c5c07d9-0014-8000-8000-000000000000
Gifts & joy 5c5c07d7-0014-8000-8000-000000000000
Health & beauty 5c5c07d2-0014-8000-8000-000000000000
Home & garden 5c5c07d4-0014-8000-8000-000000000000
Jewels & accessories 5c5c07d1-0014-8000-8000-000000000000
Kids 5c5c07d3-0014-8000-8000-000000000000
Pets & animals 5c5c07d5-0014-8000-8000-000000000000
Shopping 5c5c07da-0014-8000-8000-000000000000
Stationery & tools 5c5c07d8-0014-8000-8000-000000000000
Debt 5c5c4e20-00c8-8000-8000-000000000000
Shopping list 5c5c4e22-00c8-8000-8000-000000000000
Transfer 5c5c4e21-00c8-8000-8000-000000000000
Uncategorized 5c5c4e23-00c8-8000-8000-000000000000
Business trips 5c5c0fa3-0028-8000-8000-000000000000
Long distance 5c5c0fa2-0028-8000-8000-000000000000
Public transport 5c5c0fa0-0028-8000-8000-000000000000
Taxi 5c5c0fa1-0028-8000-8000-000000000000
Transportation 5c5c0fa4-0028-8000-8000-000000000000
Unknown expense 5c5c32c9-0082-8000-8000-000000000000
Unknown income 5c5c32c8-0082-8000-8000-000000000000
Fuel 5c5c1388-0032-8000-8000-000000000000
Insurance (Vehicle) 5c5c1392-0032-8000-8000-000000000000
Parking 5c5c1389-0032-8000-8000-000000000000
Pedaggio 5c5c1f46-0032-8000-8000-000000000000
Rentals 5c5c138b-0032-8000-8000-000000000000
Vehicle 5c5c138c-0032-8000-8000-000000000000
Vehicle maintenance 5c5c138a-0032-8000-8000-000000000000

# Filters